resource_types:
  - name: registry-image
    type: registry-image
    source:
      aws_access_key_id: ((ecr_aws_key))
      aws_secret_access_key: ((ecr_aws_secret))
      repository: registry-image-resource
      aws_region: us-gov-west-1
      tag: latest

  - name: s3-iam
    type: registry-image
    source:
      aws_access_key_id: ((ecr_aws_key))
      aws_secret_access_key: ((ecr_aws_secret))
      repository: s3-resource
      aws_region: us-gov-west-1
      tag: latest

  - name: slack-notification
    type: registry-image
    source:
      aws_access_key_id: ((ecr_aws_key))
      aws_secret_access_key: ((ecr_aws_secret))
      repository: slack-notification-resource
      aws_region: us-gov-west-1
      tag: latest

  - name: bosh-deployment
    type: registry-image
    source:
      aws_access_key_id: ((ecr_aws_key))
      aws_secret_access_key: ((ecr_aws_secret))
      repository: bosh-deployment-resource
      aws_region: us-gov-west-1
      tag: latest

  - name: bosh-io-stemcell
    type: registry-image
    source:
      aws_access_key_id: ((ecr_aws_key))
      aws_secret_access_key: ((ecr_aws_secret))
      repository: bosh-io-stemcell-resource
      aws_region: us-gov-west-1
      tag: latest

  - name: git
    type: registry-image
    source:
      aws_access_key_id: ((ecr_aws_key))
      aws_secret_access_key: ((ecr_aws_secret))
      repository: git-resource
      aws_region: us-gov-west-1
      tag: latest

resources:
  - name: jammy-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-aws-xen-hvm-ubuntu-jammy-go_agent
  - name: doomsday
    type: bosh-deployment
    source:
      target: ((bosh.target))
      client: ((bosh.client))
      client_secret: ((bosh.client-secret))
      ca_cert: ((bosh.ca-cert))
      deployment: doomsday
  - name: doomsday-deployment-src
    icon: github-circle
    type: git
    source:
      uri: ((git.source))
      branch: ((git.branch))
      commit_verification_keys: ((cloud-gov-pgp-keys))
  - name: slack
    type: slack-notification
    source:
      url: ((slack-webhook))

jobs:
  - name: reconfigure
    plan:
      - get: doomsday-deployment-src
        trigger: true
      - set_pipeline: deploy-doomsday
        file: doomsday-deployment-src/ci/pipeline.yml
        var_files:
          - doomsday-deployment-src/ci/config.yml
  - name: doomsday-deployment
    plan:
      - in_parallel:
          # this is just to trigger a deployment, the manifest specifies latest.
          - get: jammy-stemcell
            trigger: true
          - get: doomsday-deployment-src
            passed:
              - reconfigure
            trigger: true
      - put: doomsday
        params:
          stemcells:
            - jammy-stemcell/*.tgz
          manifest: doomsday-deployment-src/manifest.yml
    on_failure:
      put: slack
      params:
        text: |
          :x: Failed to deploy Doomsday in Tooling
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
        username: ((slack-user))
        icon_url: ((slack-icon-url))
